package com.example.loancalcandroid.ui.theme

import androidx.compose.ui.graphics.Color

val LoanBlueStart = Color(0xFF5B9FE8)
val LoanBlueEnd = Color(0xFF3B7FD4)
val LoanBlueDark = Color(0xFF2E6BB5)
val LoanGreen = Color(0xFF4CAF50)
val LoanRed = Color(0xFFE53935)
val ScheduleRowSelected = Color(0xFF80D7EA)
val ScheduleRowExtra = Color(0xFFFFFDEE)
val ScheduleRowOdd = Color(0xFFF4F4F4)
val SchedulePreviousBar = Color(0xFF919191)
val LoanBackground = Color(0xFFF2F2F7)
val LoanCardSurface = Color(0xFFFFFFFF)
val LoanTextSecondary = Color(0xFF8E8E93)
val LoanDivider = Color(0xFFE5E5EA)
val LoanInputBorder = Color(0xFF6C6C70)
val LoanTabSelected = Color(0xFF83D7E9)
val LoanTabUnselected = Color(0xFFE9E9E9)
val LoanTabIndicator = Color(0xFF3CB6E9)
val LoanTabDivider = Color(0xFFB6B6B6)
val OfferAccentText = Color(0xFF44B8E1)
val OfferFrameBorder = Color(0xFF1B9CE3)
val OfferButtonBackground = Color(0xFFE8F7FC)
val OfferButtonText = Color(0xFF45B8E2)
val PremiumDivider = Color(0xFFC5D5E4)
val PremiumFeaturesBackground = Color(0xFFEEFCFF)
val PremiumBuyButton = Color(0xFF83D7E9)
